version: "3.9"
services:
  botminimarketmedanos:
      container_name: botminimarketmedanos
      build: ../bot-ws-minimarket
      ports:
        - "3000:3000"
      volumes:
        - ../bot-ws-minimarket:/usr/app
  nginx:
    build: ./nginx
    expose:
      - 80
    links:
      - botminimarketmedanos
      - nginx-proxy
      - letsencrypt
    environment: 
      - VIRTUAL_HOST=minimarketlosmedanos.cl,www.minimarketlosmedanos.cl
      - LETSENCRYPT_HOST=minimarketlosmedanos.cl,www.minimarketlosmedanos.cl
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - certs:/etc/nginx/certs:ro
        - vhostd:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
    labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  
  letsencrypt:
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      environment:
          - NGINX_PROXY_CONTAINER=nginx-proxy
      volumes:
        - certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - vhostd:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
volumes:
  certs:
  html:
  vhostd: